### ISSUE TITLE
Python 3.11 wheels?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [LLNL/zfpy-wheels#10]
I see that support for Python 3.11 builds has been added yesterday: https://github.com/LLNL/zfpy-wheels/commit/ae6ca88527d01e8ffbfaaeed9c89afb10291b316 / https://github.com/LLNL/zfpy-wheels/commit/74f62bb109d3677909d2e6d40c255eadcb0ffdbe

However, wheels do not seem to be available for Python 3.11:
https://pypi.org/project/zfpy/0.5.5/#files

Attempting to build [zarr-developers/numcodecs](https://github.com/zarr-developers/numcodecs) with Python 3.11, I get errors where pip attempts to build from the C source, but building from source appears to be broken (**`build/python/zfpy.c`** is missing):
```
Installing collected packages: zfpy, snowballstemmer, pytz, alabaster, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, Pygments, mock, MarkupSafe, imagesize, docutils, babel, Jinja2, sphinx, sphinx-issues, numpydoc
  Attempting uninstall: zfpy
    Found existing installation: zfpy 1.0.0
    Uninstalling zfpy-1.0.0:
      Successfully uninstalled zfpy-1.0.0
  DEPRECATION: zfpy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for zfpy: started
  Running setup.py install for zfpy: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for zfpy did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running install
      /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'zfpy' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/build
      creating build/temp.linux-x86_64-cpython-311/build/python
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude -I/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0/x64/include/python3.11 -c build/python/zfpy.c -o build/temp.linux-x86_64-cpython-311/build/python/zfpy.o
      gcc: error: build/python/zfpy.c: No such file or directory
      gcc: fatal error: no input files
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
```
Any clue how to fix that?

**Comment by DimitriPapadopoulos** [comment]
Wheels for Python 3.11 are still missing.

I see the following error message in https://github.com/LLNL/zfpy-wheels/actions/runs/3328307226/jobs/5504502156:
```
▶ Run pypa/gh-action-pypi-publish@release/v1
[...]
Uploading distributions to https://upload.pypi.org/legacy/
Uploading zfpy-1.0.0-cp310-cp310-macosx_10_9_x86_64.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/233.3 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/233.3 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/233.3 kB • --:-- • ?
 35% ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/233.3 kB • 00:01 • 67.7 MB/s
 60% ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 139.3/233.3 kB • 00:01 • 1.8 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB • 00:00 • 1.6 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB • 00:00 • 1.6 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB • 00:00 • 1.6 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB • 00:00 • 1.6 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB • 00:00 • 1.6 MB/s
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         File already exists. See https://pypi.org/help/#file-name-reuse for    
         more information.                                           
````

**Comment by DimitriPapadopoulos** [comment]
Perhaps updating the following GitHub Actions will help:

* [`actions/checkout`](https://github.com/actions/checkout) `v2` → `v3`
  https://github.com/LLNL/zfpy-wheels/blob/74f62bb109d3677909d2e6d40c255eadcb0ffdbe/.github/workflows/wheels.yml#L14
  https://github.com/LLNL/zfpy-wheels/blob/74f62bb109d3677909d2e6d40c255eadcb0ffdbe/.github/workflows/wheels.yml#L87
* [`actions/setup-python`](https://github.com/actions/setup-python) `v2` → `v4`
  https://github.com/LLNL/zfpy-wheels/blob/74f62bb109d3677909d2e6d40c255eadcb0ffdbe/.github/workflows/wheels.yml#L19
* [`actions/upload-artifact`](https://github.com/actions/upload-artifact) `v2` → `v3`
  https://github.com/LLNL/zfpy-wheels/blob/74f62bb109d3677909d2e6d40c255eadcb0ffdbe/.github/workflows/wheels.yml#L78
* [`actions/download-artifact`](https://github.com/actions/download-artifact) `v2` → `v3`
  https://github.com/LLNL/zfpy-wheels/blob/74f62bb109d3677909d2e6d40c255eadcb0ffdbe/.github/workflows/wheels.yml#L89

**Comment by DimitriPapadopoulos** [comment]
https://pypi.org/help/#file-name-reuse

Unfortunately, it looks like you might have to bump the version of zfpy, or at least [skip existing](https://github.com/pypa/gh-action-pypi-publish#tolerating-release-package-file-duplicates) files, already uploaded:
```yaml
   with:
     skip_existing: true
```

**Comment by DimitriPapadopoulos** [comment]
Hopefully, #11 can fix the missing 3.11 wheels on some platforms.

**Comment by DimitriPapadopoulos** [comment]
Actually 3.11 wheels for version [**1.0.0**](https://pypi.org/project/zfpy/1.0.0/#files) are available:

* `zfpy-1.0.0-cp311-cp311-win_amd64.whl`
* `zfpy-1.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`
* `zfpy-1.0.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`
* `zfpy-1.0.0-cp311-cp311-macosx_11_0_arm64.whl`
* `zfpy-1.0.0-cp311-cp311-macosx_10_9_x86_64.whl`

It's just that [**1.0.0.post1**](https://pypi.org/project/zfpy/1.0.0.post1/#files) and [**1.0.0.post3**](https://pypi.org/project/zfpy/1.0.0.post3/#files) are identified as more recent versions by PyPI, but lack 3.11 wheels.

**Comment by lindstro** [comment]
@da-wad Can you please comment?

**Comment by da-wad** [comment]
Hi @DimitriPapadopoulos 

I expected that this was resolved when your issue in the main ZFP repo was closed: https://github.com/LLNL/zfp/issues/192

Testing `pip install zfpy` using Python 3.11 on my own machine gives me 1.0.0 rather than an old version or a post release, so it seems that pip is capable of resolving this without further intervention. It's unfortunate that Github Actions had (has?) no M1 runners, and that PyPI hides the fact that Python 3.11 wheels from the latest code are available.

However, in case anyone has pinned any of the 1.0.0.post* versions I am reluctant to yank them from PyPI.

**Comment by DimitriPapadopoulos** [comment]
I'll double-check what happens when un-pinning zfpy.

On Ubuntu 22.04, `pip3.10` installs `1.0.0.post3`:
```
$ pip3.10 install zfpy
Defaulting to user installation because normal site-packages is not writeable
Collecting zfpy
  Downloading zfpy-1.0.0.post3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (729 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 729.3/729.3 kB 12.2 MB/s eta 0:00:00
Installing collected packages: zfpy
Successfully installed zfpy-1.0.0.post3
$ 
```

**Comment by DimitriPapadopoulos** [comment]
After installing Python 3.11 on Ubuntu 22.04, `pip3.11` installs `1.0.0`:
```
$ pip3.11 install zfpy
Defaulting to user installation because normal site-packages is not writeable
Collecting zfpy
  Downloading zfpy-1.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.1/757.1 kB 15.5 MB/s eta 0:00:00
Installing collected packages: zfpy
Successfully installed zfpy-1.0.0
```

I am unable to reproduce any prior issues, so I am closing this issue. On the other hand, we had had issues with CI runners, no issues on my local machines.
